### ISSUE TITLE
Levantar xbuilder-server usando Quarkus tool para Maven

### ISSUE THREAD

**Issue by lsolier** [project-openubl/xbuilder-server#197]
Hola soy nuevo en Quarkus Framework, quizá este cometiendo algún error al momento de ejecutar los comandos, espero me puedan ayudar.

**Describe the bug**
Al intentar levantar **xbuilder-server** con el comando `mvnw compile quarkus:dev` obtengo el siguiente error:

_[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.550 s
[INFO] Finished at: 2020-10-14T14:40:21-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'quarkus' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\US\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException_

**To Reproduce**
Clonar repositorio local:
1. Clonar repositorio en una carpeta local utilizando un terminal (cmd, git bash, etc)
2. Ingresar a la carpeta descargada mediante el terminal 
3. Desde el terminal ejecutar comando maven `mvnw compile quarkus:dev`
4. Ver mensajes de error en el output del terminal.

**Expected behavior**
Levantar microservicio con Quarkus Framework.

**Screenshots**
![image](https://user-images.githubusercontent.com/11725705/96039293-0a5bb980-0e2e-11eb-98e9-2732cbaeda4d.png)

**Desktop:**
 - OS: Windows 10

**Additional context**
GraalVM version: **graalvm-ce-java8-20.2.0**

**Comment by carlosthe19916** [comment]
@lsolier Primero debes de asegurarte que tienes JDK 11 o superior. Una vez clonado el repositorio te ubicas en la carpeta que acabas de descargar y ejecutas:

Windows:
```
 ./mvnw.cmd quarkus:dev -f distribution/server-x/ -DnoDeps
```

o

Linux:
```
 ./mvnw quarkus:dev -f distribution/server-x/ -DnoDeps
```

> Notas:
> -  `/mvnw` es un ejecutable ubicado en el repositorio
> - Quarkus se encuentra en la carpeta `distribution/server-x` por eso es necesario usar el comando `-f distribution/server-x/ `

**Comment by lsolier** [comment]
Gracias @carlosthe19916 seguí los pasos que indicaste y logre levantar el servidor.
